[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip']

[phases.build]
cmds = ['pip install -r dashboard/requirements.txt']

[start]
cmd = 'streamlit run dashboard/app.py --server.port=$PORT --server.enableCORS=false'
