[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install -r dashboard/requirements.txt"]

[start]
cmd = "streamlit run dashboard/app.py --server.port $PORT --server.headless true"
