# nixpacks.toml

# FASE DE SETUP
# Instala las herramientas base (Python y pip)
[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

# FASE DE INSTALL
# Crea y activa el entorno virtual, luego instala las dependencias.
# Esto es análogo a la primera vez que creas tu '.env' local.
[phases.install]
cmds = ["python -m venv venv", ". venv/bin/activate && pip install -r requirements.txt"]

# FASE DE START
# Esta línea es la traducción directa de tus últimos 3 comandos locales.
[start]
cmd = ". venv/bin/activate && cd dashboard && streamlit run app.py"